name: Run Tests
on:
  workflow_dispatch:
    
  pull_request:
    paths:
      - 'src/**'
      - 'package-lock.json'
      - '.github/shared/setup/*.yaml'
      - '.github/workflows/run-tests.yaml'
      - 'Dockerfile'
    branches: 
      - main

jobs:
  unit_tests:
    timeout-minutes: 10
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/shared/setup"

      - name: Lint & Typecheck
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

  it_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: "./.github/shared/setup"

      - name: Integration Tests
        run: npm run test:it
  e2e_tests:
  # These tests are valuable because they build a container image and runs a check on the live server
  # Catch dependency update problems a lot of times that break the containier from starting up.
    timeout-minutes: 10
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "docker-compose.yaml"
          up-flags: "-d"
          down-flags: "--remove-orphans"
          services: |
            app

      - name: Test Application Health
        run: npx --yes httpyac http/health.test.http --all --var hostEndpoint="http://localhost:3002" 
